# WhatATheme
markdown: kramdown

url: https://www.windham.club
baseurl: "" # the subpath of your site, e.g. /blog

# Title of the Site
title: Windham
# Description of the Site
description: Windham is a Morris dancing group in southern Vermont
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Morris, Dancing
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/Windham-Morris-Jump.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: something@gmail.com
facebook_username: WindhamVT
#twitter_username: yakloinsteak
#instagram_username: yakloinsteak
#linkedin_username: yakloinsteak
#github_username:  yakloinsteak
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: fixme

# Disqus
disqus-shortname: yakloinsteak

# Name of the Author
author-name: Windham
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: We are Windham. Some stuff about us here.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/yakloinsteak

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalink
permalink: "news/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: 'pages'
    values:
      layout: page
  - scope:
      path: "dances"
    values:
      layout: "dance"

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
