version: '3.8'

x-app: &app
services:
  web:
    ports: ["4000:4000"]
    image: morris:latest
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        USER_ID: ${USER_ID:-10000}
        GROUP_ID: ${GROUP_ID:-10000}
    environment:
      EDITOR: vi
      HISTFILE: /log/.bash_history # TODO: test
    #command: ["bundle", "exec", "jekyll", "serve", "--livereload"]
    command: ["bundle", "exec", "jekyll", "serve", "--livereload", "--host=morris.127.0.0.1.nip.io"]
    #, "--host=0.0.0.0"]
    labels:
      - "traefik.http.routers.morris.rule=Host(`morris.127.0.0.1.nip.io`)"
      - "traefik.http.routers.morris.tls=true"
      - "traefik.enable=true"
      - "traefik.http.services.morris.loadbalancer.server.port=4000"
    volumes:
      - .:/app:cached
      #- bundle:/bundle

networks:
  default:
    name: traefik
    external: true
