name: Deploy to fly.io
on:
  push:
    branches:
    - main
    - staging

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    container: ruby:3.1.2-slim-bullseye
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          apt-get update
          apt-get install -y build-essential nodejs
          bundle install
          bundle exec middleman build
          flyctl deploy --remote-only
